In [266]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px 
import plotly.io as pio 
pio.renderers.default = "svg"

In [211]:
raw_dataset=pd.read_csv("Zomato_Mumbai_Dataset.csv",delimiter='|')

In [212]:
raw_dataset.head

<bound method NDFrame.head of                     NAME PRICE  \
0                Hitchki  1200
1           Baba Falooda   400
2          Chin Chin Chu  1800
3         Butterfly High  1000
4              BKC  DIVE  1200
...                  ...   ...
15076  Hari Om Snack Bar   350
15077           PitaBurg   400
15078     Uncha Otlawala   300
15079     Mandarin Panda   400
15080                     NaN

                                         CUSINE_CATEGORY    CITY  \
0      Modern Indian,North Indian,Chinese,Momos,Birya...  Mumbai
1                           Desserts,Ice Cream,Beverages  Mumbai
2                                          Asian,Chinese  Mumbai
3                                          Modern Indian  Mumbai
4                       North Indian,Chinese,Continental  Mumbai
...                                                  ...     ...
15076                     Fast Food,South Indian,Chinese  Mumbai
15077                                 Fast Food,Lebanese  Mumbai
15078                                 Desserts,Ice Cream  Mumbai
15079                              Desserts,Chinese,Thai  Mumbai
15080                                                NaN     NaN

                                                  REGION  \
0      First International Financial Centre-- Bandra ...
1                                                  Mahim
2                                                   Juhu
3                                   Bandra Kurla Complex
4                                   Bandra Kurla Complex
...                                                  ...
15076                                     Kandivali West
15077                                        Lower Parel
15078                                     Kandivali West
15079                                         Malad West
15080                                                NaN

                                                     URL PAGE NO  \
0      https://www.zomato.com/mumbai/hitchki-bandra-k...       1
1      https://www.zomato.com/mumbai/baba-falooda-mah...       1
2      https://www.zomato.com/mumbai/chin-chin-chu-ju...       1
3      https://www.zomato.com/mumbai/butterfly-high-b...       1
4      https://www.zomato.com/mumbai/bkc-dive-bandra-...       1
...                                                  ...     ...
15076  https://www.zomato.com/mumbai/hari-om-snack-ba...      99
15077  https://www.zomato.com/mumbai/pitaburg-lower-p...      99
15078  https://www.zomato.com/mumbai/uncha-otlawala-1...      99
15079  https://www.zomato.com/mumbai/mandarin-panda-m...      99
15080                                                NaN     NaN

          CUSINE TYPE                                         TIMING  \
0       Casual Dining                       12noon to 130am(Mon-Sun)
1      Dessert Parlor                            2pm to 1am(Mon-Sun)
2       Casual Dining                         12noon to 1am(Mon-Sun)
3                 Bar                       12noon to 130am(Mon-Sun)
4                 Bar                         1130am to 1am(Mon-Sun)
...               ...                                            ...
15076     Quick Bites                         11am to 230am(Mon-Sun)
15077            none  11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...
15078  Dessert Parlor                         9am to 1230AM(Mon-Sun)
15079            none            12noon to 330pm,7pm to 1am(Mon-Sun)
15080             NaN                                            NaN

       RATING_TYPE RATING VOTES
0        Excellent    4.9  3529
1        Very Good    4.4  1723
2        Very Good    4.2   337
3        Very Good    4.3  1200
4      Veľmi dobré    4.4  5995
...            ...    ...   ...
15076         Good    3.7    64
15077      Average    3.4    99
15078         Good    3.5    29
15079         Good    3.7   121
15080          NaN    NaN   NaN

[15081 rows x 12 columns]>

In [213]:
raw_dataset.shape

(15081, 12)

In [214]:
raw_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15081 entries, 0 to 15080
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             15081 non-null  object
 1   PRICE            15080 non-null  object
 2   CUSINE_CATEGORY  15079 non-null  object
 3   CITY             15080 non-null  object
 4   REGION           15080 non-null  object
 5   URL              15080 non-null  object
 6   PAGE NO          15080 non-null  object
 7   CUSINE TYPE      15080 non-null  object
 8   TIMING           15015 non-null  object
 9   RATING_TYPE      14070 non-null  object
 10  RATING           15080 non-null  object
 11  VOTES            15080 non-null  object
dtypes: object(12)
memory usage: 1.4+ MB

In [215]:
raw_dataset.describe()

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
count,15081,15080,15079,15080,15080,15080,15080,15080,15015,14070,15080,15080
unique,12720,67,3183,2,241,13823,944,23,2551,31,35,1124
top,NAME,400,CUSINE_CATEGORY,Mumbai,REGION,URL,PAGE NO,Quick Bites,11am to 11pm(Mon-Sun),Average,-,-
freq,942,2042,942,14138,942,942,942,5262,1192,5112,2360,2360

In [216]:
inval_page=raw_dataset['PAGE NO']=='PAGE NO'
#inval_url=raw_dataset['URL']=='URL'

In [217]:
raw_dataset[inval_page]

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
31,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
47,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
63,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
79,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
...,...,...,...,...,...,...,...,...,...,...,...,...
15000,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15016,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15032,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15048,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15064,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES

In [218]:
#raw_dataset[inval_url]

In [219]:
#The negation operator ~ excludes data which comes with inval_page criteria
raw_dataset=raw_dataset[~inval_page]

In [220]:
#Drop the columns which are not required
raw_dataset.drop(['PAGE NO', 'URL', 'CITY'],axis=1,inplace=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\3810973975.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset.drop(['PAGE NO', 'URL', 'CITY'],axis=1,inplace=True)

In [221]:
raw_dataset.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [222]:
raw_dataset.isnull().sum()

NAME                  0
PRICE                 1
CUSINE_CATEGORY       2
REGION                1
CUSINE TYPE           1
TIMING               66
RATING_TYPE        1011
RATING                1
VOTES                 1
dtype: int64

In [223]:
raw_dataset[raw_dataset['PRICE'].isnull()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
raw_dataset=raw_dataset.drop(labels=15080,axis=0)

In [225]:
raw_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995
...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am(Mon-Sun)",Good,3.5,267
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am(Mon-Sun),Good,3.7,64
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,"11am to 11pm(Mon,Tue,Wed,Thu,Sun),11am to ...",Average,3.4,99
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM(Mon-Sun),Good,3.5,29
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am(Mon-Sun)",Good,3.7,121

In [226]:
raw_dataset.fillna('NA',inplace=True)

In [227]:
raw_dataset.isnull().sum()

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
dtype: int64

In [228]:
raw_dataset['RATING'].value_counts()

RATING
-          2360
3.5        1094
3.4        1036
3.6         960
NEW         953
3.3         926
3.7         917
3.2         801
3.8         782
3.1         734
3.0         622
3.9         596
2.9         409
4.0         408
2.8         309
4.1         298
4.2         199
2.7         170
4.3         148
4.4          99
2.6          77
Opening      57
4.5          46
2.5          39
4.6          32
2.4          26
4.7          13
2.3          10
2.1           5
4.8           4
2.2           4
4.9           2
1.8           1
2.0           1
Name: count, dtype: int64

In [229]:
raw_dataset['RATING'].replace(to_replace=['-','NEW','Opening'],value='0',inplace=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\861069507.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_dataset['RATING'].replace(to_replace=['-','NEW','Opening'],value='0',inplace=True)

In [230]:
raw_dataset['VOTES'].replace(to_replace=['-','NEW','Opening'],value='0',inplace=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\995567864.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_dataset['VOTES'].replace(to_replace=['-','NEW','Opening'],value='0',inplace=True)

In [231]:
raw_dataset['PRICE']=raw_dataset['PRICE'].astype('int64')
raw_dataset['RATING']=raw_dataset['RATING'].astype('float64')
raw_dataset['VOTES']=raw_dataset['VOTES'].astype('int64')

In [232]:
raw_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  int64
dtypes: float64(1), int64(2), object(6)
memory usage: 1.1+ MB

In [233]:
str_time=raw_dataset['TIMING']

In [234]:
str_timing=raw_dataset['TIMING'].str.split("(",n=1,expand=True)

In [235]:
raw_dataset['TIMING']=str_timing[0]
raw_dataset['DAYS_OPEN']=str_timing[1]

In [236]:
raw_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun)
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun)
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun)
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun)
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun)
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267,Mon-Sun)
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am,Good,3.7,64,Mon-Sun)
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99,"Mon,Tue,Wed,Thu,Sun),11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM,Good,3.5,29,Mon-Sun)
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am",Good,3.7,121,Mon-Sun)

In [237]:
#raw_dataset['DAYS_OPEN']=raw_dataset['DAYS_OPEN'].str.replace(')',' ',regex=True)
raw_dataset['DAYS_OPEN']=raw_dataset['DAYS_OPEN'].str.replace(')','',n=1)

In [238]:
raw_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am,Good,3.7,64,Mon-Sun
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99,"Mon,Tue,Wed,Thu,Sun,11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM,Good,3.5,29,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am",Good,3.7,121,Mon-Sun

In [239]:
raw_dataset.isnull().sum()

NAME                 0
PRICE                0
CUSINE_CATEGORY      0
REGION               0
CUSINE TYPE          0
TIMING               0
RATING_TYPE          0
RATING               0
VOTES                0
DAYS_OPEN          160
dtype: int64

In [240]:
raw_dataset['DAYS_OPEN'].fillna('NA',inplace=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\2654682745.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_dataset['DAYS_OPEN'].fillna('NA',inplace=True)

In [241]:
raw_dataset.isnull().sum()

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
DAYS_OPEN          0
dtype: int64

In [242]:
raw_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  int64
 9   DAYS_OPEN        14138 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.2+ MB

In [243]:
##Remove all the records which have rating or votes 0

In [244]:
useless_data=(raw_dataset['RATING']==0.0) | (raw_dataset['VOTES']==0)

In [245]:
raw_dataset=raw_dataset[~useless_data]
raw_dataset

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Oshiwara-- Andheri West,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali West,Quick Bites,11am to 230am,Good,3.7,64,Mon-Sun
15077,PitaBurg,400,"Fast Food,Lebanese",Lower Parel,none,11am to 11pm,Average,3.4,99,"Mon,Tue,Wed,Thu,Sun,11am to ..."
15078,Uncha Otlawala,300,"Desserts,Ice Cream",Kandivali West,Dessert Parlor,9am to 1230AM,Good,3.5,29,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad West,none,"12noon to 330pm,7pm to 1am",Good,3.7,121,Mon-Sun

In [246]:
raw_dataset['RATING_TYPE'].value_counts()

RATING_TYPE
Average          5111
Good             4330
Very Good        1137
Excellent          95
Poor               47
Veľmi dobré         6
Skvělá volba        4
Dobrze              4
Bardzo dobrze       3
İyi                 2
Buono               2
Bom                 2
Muito Bom           2
Promedio            2
Dobré               2
Priemer             2
Průměr              2
Ortalama            2
Bueno               2
Excelente           1
Velmi dobré         1
Baik                1
Çok iyi             1
Skvělé              1
Média               1
Sangat Baik         1
Biasa               1
Muy Bueno           1
Media               1
Name: count, dtype: int64

In [247]:
raw_dataset['RATING_TYPE'].replace(to_replace='Excelente' , value='Excellent', inplace=True) 
raw_dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré','Bardzo dobrze','Muy Bueno','Velmi dobré'] , value='Very Good',inplace=True)
raw_dataset['RATING_TYPE'].replace(to_replace=['Skvělá volba','Dobrze','Bueno','Buono','Dobré','Bom','Skvělé'] , value='Good', inplace=True)
raw_dataset['RATING_TYPE'].replace(to_replace=['Priemer','Média','Çok iyi'] , value='Average', inplace=True) 
raw_dataset['RATING_TYPE'].replace(to_replace=['Průměr','Promedio','Ortalama','Muito Bom','İyi'] , value='Poor', inplace=True)
raw_dataset['RATING_TYPE'].replace(to_replace=['Baik','Biasa','Media','Sangat Baik'] , value='Very Poor', inplace=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_dataset['RATING_TYPE'].replace(to_replace='Excelente' , value='Excellent', inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace='Excelente' , value='Excellent', inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré','Bardzo dobrze','Muy Bueno','Velmi dobré'] , value='Very Good',inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré','Bardzo dobrze','Muy Bueno','Velmi dobré'] , value='Very Good',inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace=['Skvělá volba','Dobrze','Bueno','Buono','Dobré','Bom','Skvělé'] , value='Good', inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace=['Priemer','Média','Çok iyi'] , value='Average', inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace=['Průměr','Promedio','Ortalama','Muito Bom','İyi'] , value='Poor', inplace=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\1344611487.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['RATING_TYPE'].replace(to_replace=['Baik','Biasa','Media','Sangat Baik'] , value='Very Poor', inplace=True)

In [248]:
raw_dataset['RATING_TYPE'].value_counts()

RATING_TYPE
Average      5115
Good         4347
Very Good    1148
Excellent      96
Poor           57
Very Poor       4
Name: count, dtype: int64

In [249]:
raw_dataset['REGION']

0        First International Financial Centre-- Bandra ...
1                                                    Mahim
2                                                     Juhu
3                                     Bandra Kurla Complex
4                                     Bandra Kurla Complex
                               ...
15075                              Oshiwara-- Andheri West
15076                                       Kandivali West
15077                                          Lower Parel
15078                                       Kandivali West
15079                                           Malad West
Name: REGION, Length: 10767, dtype: object

In [251]:
#Removing the irrelevant text from the region column
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('[a-zA-Z].+-- ','',regex=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\3599048875.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('[a-zA-Z].+-- ','',regex=True)

In [252]:
 # Removing the West & East from the Region column 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace(' West| west| East| east','',regex=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\4178748503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace(' West| west| East| east','',regex=True)

In [254]:
raw_dataset['REGION'].value_counts()

REGION
Thane                726
Mira Road            412
Andheri              409
Malad                378
Kandivali            377
                    ...
Flea Bazaar Café       3
Majiwada               3
Panvel                 2
CBD Belapur            1
Girgaon Chowpatty      1
Name: count, Length: 101, dtype: int64

In [256]:
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('4 Bungalows|7 Andheri|Azad Nagar|Near Andheri Station|Veera Desai Area','Azad Nagar',regex=True)
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Bandra Kurla Complex','Bandra',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('CBD-Belapur','CBD Belapur',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Girgaon Chowpatty','Chowpatty',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Dadar Shivaji Park','Dadar',regex=True)
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Flea Bazaar Café|Kamala Mills Compound','Lower Parel',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Runwal Green','Mulund',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Mumbai CST Area','Mumbai Central',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Kopar Khairane|Seawoods|Turbhe|Ulwe','Navi Mumbai',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('New Panvel|Old Panvel','Panvel',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Kamothe','Sion',regex=True) 
raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Ghodbunder Road|Majiwada','Thane',regex=True)

C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('4 Bungalows|7 Andheri|Azad Nagar|Near Andheri Station|Veera Desai Area','Azad Nagar',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Bandra Kurla Complex','Bandra',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('CBD-Belapur','CBD Belapur',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Girgaon Chowpatty','Chowpatty',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Dadar Shivaji Park','Dadar',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Flea Bazaar Café|Kamala Mills Compound','Lower Parel',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Runwal Green','Mulund',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Mumbai CST Area','Mumbai Central',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Kopar Khairane|Seawoods|Turbhe|Ulwe','Navi Mumbai',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('New Panvel|Old Panvel','Panvel',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Kamothe','Sion',regex=True)
C:\Users\Dayana\AppData\Local\Temp\ipykernel_19792\194110425.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_dataset['REGION'] = raw_dataset['REGION'].str.replace('Ghodbunder Road|Majiwada','Thane',regex=True)

In [258]:
raw_dataset['REGION'].value_counts()

REGION
Thane           770
Mira Road       412
Andheri         409
Malad           378
Kandivali       377
               ...
Malabar Hill     14
Sewri            12
Alibaug          10
Gorai             7
Peddar Road       4
Name: count, Length: 81, dtype: int64

In [259]:
raw_dataset[raw_dataset.duplicated()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
4064,Sai Sannidhi Restaurant & Bar,1000,"North Indian,Konkan",Dahisar,Casual Dining,11am to 12midnight,Good,3.7,99,Mon-Sun
4068,Konkan Katta,400,"Seafood,Maharashtrian,Malwani",Mahakali,Quick Bites,"11am to 330pm,630pm to 1130pm",Good,3.5,181,Mon-Sun
4082,Usmaniya Hotel,600,Mughlai,Fort,Casual Dining,1030am to 1130pm,Average,3.2,8,Mon-Sun
4083,Gina's Cakes,450,Bakery,Dombivali,none,11am to 11pm,Good,3.5,49,Mon-Sun
4084,Konkanastha Lunch Home,400,"Seafood,Malwani",Chakala,Casual Dining,"12noon to 3pm,730pm to 1030pm",Good,3.5,44,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14200,Mezbaan Family Restaurant,350,"Chinese,Mughlai",Mumbra,Dhaba,12noon to 1230AM,Average,2.8,97,Mon-Sun
14204,Jyoti Lunch Home,650,"Chinese,North Indian,Seafood,Mughlai",Mulund,Casual Dining,11am to 1230AM,Good,3.5,49,Mon-Sun
14253,On Toes,900,"Italian,North Indian,Chinese",Malad,Casual Dining,"12noon to 3pm,7pm to 1230AM",Good,3.6,76,Mon-Sun
14761,Frosty Farm,400,"Ice Cream,Desserts,Fast Food",Malad,Dessert Parlor,1pm to 1215AM,Good,3.6,120,Mon-Sun
14928,Shree Manu Sagar,300,"North Indian,Chinese,Indian",Ghansoli,Quick Bites,"1130am to 415pm,7pm to 1215AM",Average,3.3,51,Mon-Sun

In [260]:
raw_dataset=raw_dataset.drop_duplicates()

In [261]:
zomato_dataset=raw_dataset.copy()

In [262]:
zomato_dataset.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar,1130am to 1am,Very Good,4.4,5995,Mon-Sun

In [274]:
#Exploratory Data Analysis  
#1. HOW MANY RESTAURANTS ARE IN MUMBAI FOR EACH CUSINE TYPE?

In [289]:
fig=px.histogram(zomato_dataset, x='CUSINE TYPE', color='CUSINE TYPE',  
                   title= 'No. of Restaurants by Cusine Type',  
                   labels={'CUSINE TYPE':'Cusine Type'}) 
 
fig.show()

ValueError:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido

In [288]:
!pip install -U kaleido

Requirement already satisfied: kaleido in c:\users\dayana\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: choreographer>=1.3.0 in c:\users\dayana\anaconda3\lib\site-packages (from kaleido) (1.3.0)
Requirement already satisfied: logistro>=1.0.8 in c:\users\dayana\anaconda3\lib\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\dayana\anaconda3\lib\site-packages (from kaleido) (3.11.9)
Requirement already satisfied: packaging in c:\users\dayana\anaconda3\lib\site-packages (from kaleido) (24.2)
Requirement already satisfied: platformdirs>=4.3.6 in c:\users\dayana\anaconda3\lib\site-packages (from choreographer>=1.3.0->kaleido) (4.3.7)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\dayana\anaconda3\lib\site-packages (from choreographer>=1.3.0->kaleido) (4.1.1)

In [ ]:
#2.How to Categorize the restaurants in Mumbai with the rating type?

In [301]:
rating_type_df = zomato_dataset['RATING_TYPE'].value_counts().reset_index() 
rating_type_df.rename(columns={'index':'RATING TYPE', 'RATING_TYPE':'RATING CATEGORY'}, inplace=True) 
rating_type_df

  RATING CATEGORY  count
0         Average   4983
1            Good   4263
2       Very Good   1145
3       Excellent     96
4            Poor     56
5       Very Poor      4

In [304]:
fig = px.pie(rating_type_df, names='RATING TYPE', values='COUNT OF RESTAURANTS', color='RATING TYPE',  
             title='Percentage of Restaurants by Rating Type').update_traces(textposition='inside', textinfo='percent+label')
fig.show()

ValueError: Value of 'names' is not the name of a column in 'data_frame'. Expected one of ['RATING CATEGORY', 'count'] but received: RATING TYPE

In [309]:
# Which are the Top 10 highest rated Seafood Restaurant in Mumbai?

In [307]:
seafood_df = zomato_dataset[zomato_dataset['CUSINE_CATEGORY'].str.contains('Seafood')] 
seafood_df.sort_values(by='RATING',ascending=False).head(10)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
7104,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",Khar,Bar,"12noon to 4pm,7pm to 3am",Excellent,4.7,564,Mon-Sun
76,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",Thane,Casual Dining,1130am to 1130pm,Excellent,4.6,350,Mon-Sun
13685,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",Kharghar,Casual Dining,"11am to 345pm,7pm to 1145pm",Excellent,4.6,209,Mon-Sun
9954,Pi Bar and Kitchen,1600,"Continental,European,Italian,Seafood,Pizza,Des...",Andheri,Bar,"12noon to 6pm,7pm to 12midnight",Excellent,4.5,2068,Mon-Sun
884,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining,11am to 11pm,Excellent,4.5,178,Mon-Sun
12433,Quarter Canteen,1100,"North Indian,Seafood,Chinese",Bandra,Casual Dining,"12noon to 330pm,7pm to 1am",Excellent,4.5,573,Mon-Sun
3380,Peco Peco,700,"Chinese,Seafood,Asian",Powai,none,"12noon to 330pm,7pm to 1230AM",Excellent,4.5,497,Mon-Sun
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",Bandra,Casual Dining,12noon to 1am,Excellent,4.5,100,Mon-Sun
915,Monis Bar and Restaurant,1000,"North Indian,Chinese,Continental,Seafood,Bever...",Thane,Casual Dining,"1130am to 330pm,6pm to 1130pm",Very Good,4.4,662,Mon-Sun
8890,Hardeep Punjab,1100,"North Indian,Chinese,Mughlai,Seafood",Sion,Casual Dining,11am to 1am,Very Good,4.4,871,Mon-Sun